### ISSUE TITLE
Host should be configurable

### ISSUE THREAD

**Issue by msmith-techempower** [MTDdk/jawn#10]
[This line](https://github.com/MTDdk/jawn/blob/master/jawn-server-undertow/src/main/java/net/javapla/jawn/server/UndertowServer.java#L55) in particular causes problems when 'localhost' does not loopback correctly.

Most other implementations I have seen default to `0.0.0.0` to get around the name issues.

Suggestion: add `getHost` and `setHost` to `ServerConfig.java` and use the value in place of the the 'localhost' on the above linked line. This would allow `config.setHost('0.0.0.0')` which should get around this particular issue.

**Comment by MTDdk** [comment]
A fix has been issued to the existing pull request

**Comment by msmith-techempower** [comment]
Thanks for the quick turnaround on this! :+1:

**Comment by MTDdk** [comment]
Sure thing!
Just looking forward to see it in action in the next round
